### ISSUE TITLE
ZKL fails to install engines from portable.7z

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1070]
``` 
2016-06-19 1:58:53 PM: Download started: 101.0.1-414-g6a6a528
2016-06-19 1:58:55 PM: Downloading http://springrts.com/dl/buildbot/default/develop/101.0.1-414-g6a6a528/win32/spring_101.0.1-414-g6a6a528_portable.7z
2016-06-19 1:59:44 PM: Installing http://springrts.com/dl/buildbot/default/develop/101.0.1-414-g6a6a528/win32/spring_101.0.1-414-g6a6a528_portable.7z
2016-06-19 1:59:45 PM: Install of 101.0.1-414-g6a6a528 failed: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at PlasmaDownloader.EngineDownload.<>c__DisplayClass3_1.<Start>b__2(Object s, AsyncCompletedEventArgs e)
```

**Comment by Licho1** [comment]
ZKL cannot decompress 7z, it wont work. On linux it works using commandline tool. We need to repack and put on a mirror.
