### ISSUE TITLE
Lobby fails to load engine when disconnected

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K-Infrastructure#1115]
With the new lobby if you try to run the game in skirmish mode, spring won't start unless you're connected to the site. It says 'spring starting' but nothing actually happens. After checking the error log I believe this bit is the culprit:

`
7/19/2016 5:49 AM
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
   at LobbyClient.ScriptGenerator.GeneratePlayerSection(StringBuilder script, BattleContext startContext, SpringBattleStartSetup setup)
   at LobbyClient.ScriptGenerator.GenerateHostScript(BattleContext startContext, SpringBattleStartSetup startSetup, Int32 loopbackListenPort, String zkSearchTag, String host, Int32 port, String myname, String mypassword)
   at LobbyClient.Spring.HostGame(BattleContext context, String host, Int32 port, String myName, String myPassword)
   at ZeroKLobby.MicroLobby.ExtrasTab.SkirmishControl.Event_Startbutton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by Licho1** [comment]
Skirmisher is gone, replacement in progress..
