### ISSUE TITLE
#springielives

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1143]
Test Springie is still running, but it is not functional.

```
[17:00:24]	<*>	Platinum Hi Anarchid (rights:0), welcome to Springie 0.0.0.891, automated host. For help say !help
[17:00:25]	<*>	Platinum ServerManage error: System.ServiceModel.ServiceActivationException: The requested service, 'http://test.zero-k.info/SpringieService.svc' could not be activated. See the server's diagnostic trace logs for more information.
[17:00:25]	<*>	Platinum 
[17:00:25]	<*>	Platinum Server stack trace: 
[17:00:25]	<*>	Platinum    at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
[17:00:25]	<*>	Platinum    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
[17:00:26]	<*>	Platinum    at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
[17:00:26]	<*>	Platinum    at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
[17:00:26]	<*>	Platinum    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
[17:00:26]	<*>	Platinum    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
[17:00:27]	<*>	Platinum    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
[17:00:27]	<*>	Platinum 
[17:00:27]	<*>	Platinum Exception rethrown at [0]: 
[17:00:27]	<*>	Platinum    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[17:00:27]	<*>	Platinum    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[17:00:27]	<*>	Platinum    at PlasmaShared.ISpringieService.AutohostPlayerJoined(BattleContext context, Int32 accountID)
[17:00:28]	<*>	Platinum    at Springie.autohost.AutoHost.tas_BattleUserJoined(Object sender, BattleUserEventArgs e1)
```

**Comment by Licho1** [comment]
fixed by turning it off
