### ISSUE TITLE
No XP/Elo after game end - linq/database issue

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K-Infrastructure#121]
We've played a game over an hour and after it has been over we got an error - no elo/xp change was recorded

[12:39]  Springiee2 [[G0G0]Dancer]!vote 1
[12:39]  * Springiee2 Poll: Resign team 1? [END:SUCCESS]
[12:39]  Springiee2 [_edrush]!vote 1
[12:39]  * Springiee2 Game over, exiting
[12:39]  * Springiee2 System.Data.Linq.DuplicateKeyException: Cannot add an entity with a key that is already in use.
[12:39]  * Springiee2    at System.Data.Linq.ChangeProcessor.TrackUntrackedObjects(MetaType type, Object item, Dictionary`2 visited)
[12:39]  * Springiee2    at System.Data.Linq.ChangeProcessor.TrackUntrackedObjects()
[12:39]  * Springiee2    at System.Data.Linq.ChangeProcessor.SubmitChanges(ConflictMode failureMode)
[12:39]  * Springiee2    at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
[12:39]  * Springiee2    at ZkData.ZkDataContext.SubmitAndMergeChanges() in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Shared\PlasmaShared\Data\ZkData.cs:line 73
[12:39]  * Springiee2    at ZeroKWeb.SpringieInterface.BattleResultHandler.SubmitSpringBattleResult(BattleContext context, String password, BattleResult result, List`1 players, List`1 extraData) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\ZeroK.info\SpringieInterface\BattleResultHandler.cs:line 162

[12:39]  * Springiee2 changing map to Mescaline_V2
[12:39]  * Springiee2 changing map to TheBeachBeta

**Comment by Licho1** [comment]
Dont seem to be happening anymore
