### ISSUE TITLE
Unitsync-related errors on server ("bad image format")

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1405]
Yesterday and today ZKLS stopped allowing logins somewhere past 10 AM GMT.

Restarting the zkinfo site in IIS solved the problem.

Event log contained the following three seemingly relevant messages:

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at ZkData.UnitSyncLib.UnitSync+NativeMethods.UnInit()
   at ZkData.UnitSyncLib.UnitSync.Dispose()
   at ZkData.UnitSyncLib.UnitSync.Finalize()
```

```
Faulting application name: w3wp.exe, version: 8.0.9200.16384, time stamp: 0x5010885f
Faulting module name: KERNELBASE.dll, version: 6.2.9200.21815, time stamp: 0x56eafe4e
Exception code: 0xe0434352
Fault offset: 0x00017f2a
Faulting process id: 0x1a6c
Faulting application start time: 0x01d27ba7fc453497
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 4acd5cbc-e79b-11e6-93f1-4c72b926259e
Faulting package full name: 
Faulting package-relative application ID: 
```

```
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/7/ROOT

Process ID: 6764

Exception: System.BadImageFormatException

Message: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

StackTrace:    at ZkData.UnitSyncLib.UnitSync.NativeMethods.UnInit()
   at ZkData.UnitSyncLib.UnitSync.Dispose()
   at ZkData.UnitSyncLib.UnitSync.Finalize()
```

**Comment by Anarchid** [comment]
Unrelated to reason of outage.

**Comment by Licho1** [comment]
still must be fixed as this is test verison, to be deployed next stable.

**Comment by Anarchid** [comment]
I consider this to be a duplicate of #1401 now. No reason to keep both open IMO.

**Comment by Licho1** [comment]
fixed (reupload 32bit engine to test site)
