### ISSUE TITLE
Plasma error on search: "System.ArgumentException: An item with the same key has already been added."

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#146]
http://buildbot.springrts.com/builders/validationtests/builds/4376/steps/validation%20test%20prepare/logs/stdio

[Error] ../../tools/pr-downloader/src/Downloader/Plasma/PlasmaDownloader.cpp:29:search(): Soap error: 12: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Data.Linq.ChangeTracker.StandardChangeTracker.PromoteFastTrackedObject(Object obj)
   at System.Data.Linq.ChangeTracker.StandardChangeTracker.OnPropertyChanging(Object sender, PropertyChangingEventArgs args)
   at ZkData.Resource.SendPropertyChanging() in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Shared\PlasmaShared\Data\ZkData.designer.cs:line 8590
   at ZkData.Resource.set_LastLinkCheck(Nullable`1 value) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Shared\PlasmaShared\Data\ZkData.designer.cs:line 8175
   at ZeroKWeb.ResourceLinkProvider.UpdateLinks(ResourceContentFile content) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Zero-K.info\AppCode\ResourceLinkProvider.cs:line 256
   at ZeroKWeb.ResourceLinkProvider.<>c__DisplayClass16.<GetLinksAndTorrent>b__a() in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Zero-K.info\AppCode\ResourceLinkProvider.cs:line 156
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at ZeroKWeb.ResourceLinkProvider.GetLinksAndTorrent(String internalName, List`1& links, Byte[]& torrent, List`1& dependencies, ResourceType& resourceType, String& torrentFileName) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Zero-K.info\AppCode\ResourceLinkProvider.cs:line 156
   at ZeroKWeb.PlasmaServer.DownloadFile(String internalName, List`1& links, Byte[]& torrent, List`1& dependencies, ResourceType& resourceType, String& torrentFileName) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Zero-K.info\AppCode\PlasmaServer.cs:line 52
   at ZeroKWeb.ContentService.DownloadFile(String internalName, List`1& links, Byte[]& torrent, List`1& dependencies, ResourceType& resourceType, String& torrentFileName) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Zero-K.info\ContentService.asmx.cs:line 47
   --- End of inner exception stack trace ---

**Comment by Licho1** [comment]
it was caused by duplicate mirror list i think its fixed
