### ISSUE TITLE
zk-v1.5.9.4 Does not download

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1818]
Infolog_full:
chobby.exe Information: 0 : Checking for self-upgrade
chobby.exe Error: 0 : http://zk.repo.springrts.com/builds/zk-v1.5.9.4.sdz failed System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
chobby.exe Error: 0 : http://zk.repo.springrts.com/builds/zk-v1.5.9.4.sdz failed System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
chobby.exe Error: 0 : http://zk.repo.springrts.com/builds/zk-v1.5.9.4.sdz failed System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

**Comment by KingRaptor** [comment]
Fixed for the specific case.

Future stables will require the .sdz to be uploaded by FTP to zero-k.info/builds, until a74ad858d6283a7d10e5cbc19ffd8b17b8312a0b goes live.
