### ISSUE TITLE
Test branch steam does not launch

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1873]
It seems to be looking for the wrong zkmenu. Here is the full infolog.

Zero-K.exe Information: 0 : Reseting configs and deploying AIs
Zero-K.exe Error: 0 : Unexpected error: System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Zero-K\pool\d5\3342a4849c77606a0f701e9c0510db.gz'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\Zero-K\pool\d5\3342a4849c77606a0f701e9c0510db.gz'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ZkData.Pool.ReadFromStorageDecompressed(Hash hash)
   at PlasmaDownloader.Packages.PackageDownloader.Version.ReadFile(SpringPaths paths, String namePath)
   at PlasmaDownloader.ConfigVersions.LoadFromChobby(Version ver, SpringPaths paths)
   at PlasmaDownloader.ConfigVersions.DeployAndResetConfigs(SpringPaths paths, Version ver)
   at ChobbyLauncher.Chobbyla.<Prepare>d__22.MoveNext()
Zero-K.exe Information: 0 : Unexpected error preparing chobby launch: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Zero-K\pool\d5\3342a4849c77606a0f701e9c0510db.gz'.

I have a file called 0fd4926d8858bbef871594b6f4a93d04.sdz that looks like zkmenu when opened. #

**Comment by Licho1** [comment]
fixed
