### ISSUE TITLE
Discord timestamp does not work

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1962]
Discord isn't in ISO standard or something else is failing.

[f=-000001] [GR::LogDisplayMode] display-mode set to 960x810x24bpp@75Hz (windowed::decorated)
chobby.exe Error: 0 : ChobbyLauncher.ChobbylaLocalListener error processing line DiscordUpdatePresence {"state":"In Menu","startTimestamp":"2017-12-19T05:44:41","details":"In Menu"} : Newtonsoft.Json.JsonSerializationException: Error converting value 19/12/2017 5:44:41 AM to type 'System.Int64'. Path 'startTimestamp', line 1, position 57. ---> System.InvalidCastException: Invalid cast from 'DateTime' to 'Int64'.
   at System.DateTime.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at PlasmaShared.CommandJsonSerializer.DeserializeLine(String line)
   at ChobbyLauncher.ChobbylaLocalListener.<OnCommandReceived>d__27.MoveNext()
chobby.exe Error: 0 : ChobbyLauncher.ChobbylaLocalListener error processing line DiscordUpdatePresence {"state":"In Menu","startTimestamp":"2017-12-19T05:44:41","details":"In Menu"} : Newtonsoft.Json.JsonSerializationException: Error converting value 19/12/2017 5:44:41 AM to type 'System.Int64'. Path 'startTimestamp', line 1, position 57. ---> System.InvalidCastException: Invalid cast from 'DateTime' to 'Int64'.
   at System.DateTime.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at PlasmaShared.CommandJsonSerializer.DeserializeLine(String line)
   at ChobbyLauncher.ChobbylaLocalListener.<OnCommandReceived>d__27.MoveNext()
[f=-000001] SteamOnline, Received

**Comment by Licho1** [comment]
You can notice that times in this structure are "long"
        public long startTimestamp;
        public long endTimestamp;

Both in messages and in discord docs - this is just a replica of discord official API.
It should be unix time (number of seconds since 1.1.1970).
