### ISSUE TITLE
whois failure

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#197]
[5:11 AM]  Nightwatch System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
[5:11 AM]  Nightwatch    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
[5:11 AM]  Nightwatch    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
[5:11 AM]  Nightwatch    --- End of inner exception stack trace ---
[5:11 AM]  Nightwatch    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
[5:11 AM]  Nightwatch    at System.IO.StreamReader.ReadBuffer()
[5:11 AM]  Nightwatch    at System.IO.StreamReader.ReadToEnd()
[5:11 AM]  Nightwatch    at PlasmaShared.Whois.QueryWhois(String command) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Shared\PlasmaShared\Whois.cs:line 35
[5:11 AM]  Nightwatch    at PlasmaShared.Whois.QueryByIp(String ip, Boolean useGRS) in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\Shared\PlasmaShared\Whois.cs:line 18
[5:11 AM]  Nightwatch    at NightWatch.AuthService.<>c__DisplayClass23.<>c__DisplayClass29.<.ctor>b__a() in c:\TeamCity\buildAgent\work\b8c78a57f4c14bae\NightWatch\AuthService.cs:line 204

This caused me to have a look and basically:
- 1 whois query is generated for each user connecting to uberserver
- no caching of result (some code is there but it is not used)
- no connection pooling or limits
- no respect of data provider (RIPE) acceptable use policy
(I omit potential problems due to SOAP)

with the number of players connecting to uberserver each day, 1000 queries/day are probably reached quickly...
=> is RIPE annoyed by reckless queries? that could cause those exceptions...

what happens if RIPE starts throttling queries in a way that hang connections rather than use TCP reset or closing connection without answering? more threads hanging!

**Comment by Licho1** [comment]
appears fixed
