### ISSUE TITLE
Mission editor does not work

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2605]
One issue may be that the way customKeys work was changed since 104-287. The change may be restricted to lua.

See https://steamcommunity.com/app/334920/discussions/0/1644295067087792009/

**Comment by Histidine91** [comment]
```
Version: 2.6.1.0
Date: 2019-07-24 7:16:19 PM
UnitSyncException
Exception of type 'CMissionLib.UnitSyncLib.UnitSyncException' was thrown.
   at CMissionLib.UnitSyncLib.UnitSync.ReadUnits()
   at CMissionLib.UnitSyncLib.UnitSync.GetMod(String modName)
   at MissionEditor2.WelcomeDialog.LoadMod(UnitSync unitSync, String modName)
   at MissionEditor2.WelcomeDialog.<>c__DisplayClass12_0.<LoadExistingMission>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
Looks like an issue in editor's unitsync library. I examined it some months ago but was unable to figure out why it's occurring or how to fix it.
