### ISSUE TITLE
ZKL crashes while ingame after starting a game through 1v1 queue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#334]
ZeroKLobbyErrors.txt contains no entry for the relevant time. Here are the entries for the day.

===============
6/01/2015 12:21 PM
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

===============
6/01/2015 12:24 PM
System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at PlasmaShared.Connection.SendCommand(String command, Object[] parameters)

===============
6/01/2015 12:26 PM
System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

===============
6/01/2015 1:27 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.TcpClient'.
   at System.Net.Sockets.TcpClient.GetStream()
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

**Comment by GoogleFrog** [comment]
Perhaps relevant errors are in here

===============
6/01/2015 2:19 PM
System.NullReferenceException: Object reference not set to an instance of an object.
   at LobbyClient.TasClient.DispatchServerCommandOnGuiThread(String command, String[] args)

===============
6/01/2015 2:21 PM
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

===============
6/01/2015 2:24 PM
System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at PlasmaShared.Connection.SendCommand(String command, Object[] parameters)

===============
6/01/2015 2:26 PM
System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

**Comment by Licho1** [comment]
Was it in 2:19 ? If not there are no relevant data just random network failure :(
