### ISSUE TITLE
ZKL grey rectangle chat

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#337]
Special characters in a commit message caused the chat to be replaced with a grey rectangle.
![zklgreyrectangle](https://cloud.githubusercontent.com/assets/1318249/5627655/7b310ca4-95ef-11e4-9d2e-02a2769cd257.jpg)

or (master...zkl_fixPlayerlistScrollFlicker) http://git.io/XVipHA
[9:54 PM]  zkgit [Zero-K-Infrastructure] Licho1 pushed 1 new commit to contentservice_rewri: http://git.io/gAjRIQ

**Comment by xponen** [comment]
this is a crash due to this char, the error should appear in Diagnostic log, can you help paste the content? (preferably any red message)

**Comment by GoogleFrog** [comment]
===============
6/01/2015 8:43 PM
System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at PlasmaShared.Connection.DataRecieveCallback(IAsyncResult res)

===============
6/01/2015 9:56 PM
FATAL: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

===============
6/01/2015 10:29 PM
System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: http://tempuri.org/GetResourceData.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at PlasmaShared.ContentService.ContentService.GetResourceData(String md5, String internalName)
   at PlasmaShared.SpringScanner.GetResourceData(WorkItem work)

===============
6/01/2015 10:31 PM
System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: http://tempuri.org/GetResourceData.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at PlasmaShared.ContentService.ContentService.GetResourceData(String md5, String internalName)
   at PlasmaShared.SpringScanner.GetResourceData(WorkItem work)

===============
6/01/2015 10:33 PM
System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: http://tempuri.org/GetResourceData.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at PlasmaShared.ContentService.ContentService.GetResourceData(String md5, String internalName)
   at PlasmaShared.SpringScanner.GetResourceData(WorkItem work)

**Comment by Licho1** [comment]
Those logs are due to outdated ZKL.. someone broke self updater apparently
so it does not popup..

2015-01-06 12:34 GMT+01:00 GoogleFrog <notifications@github.com>:

**Comment by GoogleFrog** [comment]
Then there is no crash appearing in the logs.

**Comment by Anarchid** [comment]
Self-updater seems to have been broken sometime in the past; visiting my windows partition today had ZKL freeze upon downloading updates.

**Comment by Licho1** [comment]
amazing...
