### ISSUE TITLE
BUG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by google45** [ZeroK-RTS/Zero-K-Infrastructure#591]
http://temporary-link-x-use-i-dot-snaggy-for-hotlinking-x-3295a434ffc3.snag.gy/k3Dwp.jpg

all of a sudden this happened, screen shot to prove it, #zk is all grey and idk why.
it started when I log in today, and it was grey :P. so help me fix this bug so I can see all
the nice ppl chats :D. and thanks, also my Lobby Diagnostic Log, don't know what to do with it, but I'll just paste all of it :p.

```
4/14/2015 8:42:16 PM: Starting with version 1.3.2.62
4/14/2015 8:42:16 PM: Using Internet Explorer 10
4/14/2015 8:42:16 PM: SpringPaths: SPRING_DATADIR: C:\Users\Angus\Downloads;C:\Users\Angus\Documents\My Games\Spring
4/14/2015 8:42:16 PM: SpringPaths: SPRING_WRITEDIR: C:\Users\Angus\Downloads
4/14/2015 8:42:16 PM: SpringPaths: SPRING_ISOLATED: C:\Users\Angus\Downloads
4/14/2015 8:42:16 PM: SpringPaths: SPRING_DATADIR: C:\Users\Angus\Downloads;C:\Users\Angus\Documents\My Games\Spring;C:\Users\Angus\Downloads\engine\98.0.1-451-g0804ae1;C:\Users\Angus\Downloads\engine
4/14/2015 8:42:16 PM: SpringPaths: SPRING_WRITEDIR: C:\Users\Angus\Downloads
4/14/2015 8:42:16 PM: SpringPaths: SPRING_ISOLATED: C:\Users\Angus\Downloads
4/14/2015 8:42:18 PM: System DPI Value: dpiX= 96, dpiY= 96
4/14/2015 8:42:18 PM: Initial scan done
4/14/2015 8:42:25 PM: TASC connected
4/14/2015 8:42:26 PM: TASC login accepted
4/14/2015 8:42:26 PM: Server is using Spring version 98.0.1-451-g0804ae1
4/14/2015 8:42:28 PM: TASC channel joined: zk
4/14/2015 8:42:28 PM:    at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.AppendText(String newLine, Int32 color): AppendText Error:A generic error occurred in GDI+.
4/14/2015 8:42:28 PM: TASC channel joined: clan_ZKW
4/14/2015 8:42:28 PM: TASC channel joined: Rising
4/14/2015 8:42:28 PM: TASC channel joined: en
4/14/2015 8:42:37 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:42:37 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:42:37 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:42:49 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:42:49 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:43:12 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:43:12 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:43:22 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:43:22 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:45:24 PM: Joining battle 9
4/14/2015 8:45:28 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:28 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:29 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:33 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:36 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:36 PM: Error generating player context menu: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at ZeroKLobby.MicroLobby.ContextMenus.GetPlayerContextMenu(User user, Boolean isBattle)
4/14/2015 8:45:43 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:43 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:45 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:45:45 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:45 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:52 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:52 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:45:53 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:45:53 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:45:53 PM: FATAL: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.ReturnWord(Int32 lineNumber, Int32 x)
   at ZeroKLobby.MicroLobby.TextWindow.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
4/14/2015 8:50:44 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:50:44 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:50:46 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:50:46 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:52:05 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
4/14/2015 8:52:05 PM:    at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, Single x, Single y, StringFormat format)
   at ZeroKLobby.MicroLobby.TextWindow.OnDisplayText(PaintEventArgs e): TextWindow OnDisplayText Error:A generic error occurred in GDI+.
```

**Comment by xponen** [comment]
reported by google as it fixed itself.
