### ISSUE TITLE
rapid download - leak open connections (TCP Zero window condition)

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#614]
This is a bug showing some problem in the handling of rapid downloads.

What exactly is happening is not yet clear, but it is easy to trigger and easy to confirm. It is not clear how it affects people not clicking like madmen (see below)...

1) install wireshark
2) start traffic capture
3) in zkl, go to rapid tab... rapidly double-click multiple times on something to download... for example zk:test
4) if you see download bars in ZKL stuck, not downloading anything... you successfully triggered the problem
5) use the following wireshark filter:

(ip.dst == 78.46.100.157 || ip.src == 78.46.100.157) && tcp.port == 80

wait a bit... and watch. When you see packets flagged with TCP ZeroWindow, read up here:

http://wesmorgan.blogspot.ch/2011/03/tcp-zero-windows-and-why-they-can-be.html

Zero window condition will last...

Its probably easy to just prevent the double-clicks... but maybe there is something to investigate in the network. Player reports of stuck downloads can be found...

Suspect code:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/Packages/PackageDownload.cs#L117

Note: I kept the stuck download bar open while writing this issue. I closed it now, expecting that connection would be closed, but it does not. Connection is kept open, confirmed with "netstat -tn".

After closing the download bar, I opened the rapid tab again, then double-clicked on some tag.
ZKL hangs... then connection to zk lobby server is dropped.

**Comment by shaun0x00** [comment]
Strange things are even stranger.
I wanted to close the 2 connections in order to release server resources, so I did something logical: close ZKL.

Then checked with "netstat -tno", just to be sure. Connections were still here!

So, either my report is completely wrong... or something even stranger is happening behind the scenes. Indeed, there was a 2nd Zero-K.exe process... who kept the connection open.

Not sure what that is... but after killing this process, connections are released.

Where is this 2nd process coming from?

**Comment by shaun0x00** [comment]
After a few tests, it seems Zero-K.exe doesn't really exit... it just hides the window. Does that happen because of the stuck downloads?

**Comment by shaun0x00** [comment]
from trace log:

5/10/2015 7:01:05 PM: System.IO.IOException: The process cannot access the file 'C:\Users\user\Documents\My Games\Spring\pool\ee\3447844aee00d6cee5e17b43193d00.gz' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at ZkData.Pool.PutToStorage(Byte[] data, Hash hash)
   at PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
5/10/2015 7:01:05 PM: Error downloading XTAR V1.03: System.IO.IOException: The process cannot access the file 'C:\Users\user\Documents\My Games\Spring\pool\ee\3447844aee00d6cee5e17b43193d00.gz' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at ZkData.Pool.PutToStorage(Byte[] data, Hash hash)
   at PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
5/10/2015 7:01:34 PM: XTAR V1.03 download failed - unexpected endo fo stream

**Comment by shaun0x00** [comment]
5/10/2015 7:02:43 PM: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
5/10/2015 7:02:43 PM: Error downloading XTAR V1.03: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)

**Comment by shaun0x00** [comment]
Dispose() is never called as explained here:

https://stackoverflow.com/questions/1968522/c-using-statements-with-httpwebrequests-httpwebresponses

and it does "return false" when there is a problem. Of course the connection stays open.

This can happen when write to disk fails (disk full, simultaneous access as shown above).

Could this be triggered by 2 archive downloads depending on the same files, causing the same consequences as here?

**Comment by Licho1** [comment]
Dispose is automatically called when the instance is garbage collected (this can take up to several minutes depending on application memory profile)

**Comment by shaun0x00** [comment]
Its not. These leaked connections are not closed by the garbage collector, they are kept alive until process is killed (lived for more than 30 minutes).

**Comment by xponen** [comment]
Just prevent duplicate download will fix this.

I've check and found the following code failed to return true:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/PlasmaDownloader.cs#L104

The requested download (eg: "zk:test") never matched existing download name (eg: Zero-K test-xxxx), so the duplicate check failed
----

I assign myself to fix this bug, but not the network stuff.
Connection close normally for me most of time. Very rarely ZKL failed to exit completely

**Comment by xponen** [comment]
I screen cap ZKL connections.
I make no judgement, just sharing

ZKL startup, mandatory rapidlist update
![zklports_startup](https://cloud.githubusercontent.com/assets/2525365/7590550/bf9984a6-f8fb-11e4-8396-29e735515e96.jpg)

ZKL login, loading Home page (soo many stuff!)
![zklports_login](https://cloud.githubusercontent.com/assets/2525365/7590571/dbdff3ac-f8fb-11e4-9bbe-b4f90a90a4c9.jpg)

ZKL idling, chats/room
![zklports_chatting](https://cloud.githubusercontent.com/assets/2525365/7590595/f1f603de-f8fb-11e4-9851-5ca8a3528529.jpg)

ZKL downloading new mods, mandatory rapidlist update (if > 2 minute old)
![zklports_downloadingmod](https://cloud.githubusercontent.com/assets/2525365/7590628/1b90c6f2-f8fc-11e4-923e-d56e656195a0.jpg)

**Comment by shaun0x00** [comment]
@xponen please explain how the proposed change is actually making any difference?

Does it prevent 2 files with same hash from being written at the same time by 2 simultaneous mods (different) downloads, or does it only compare the mod names? Isn't it possible that 2 mods, such as zk:test and zk:stable would depend on the same content, so, contain the a few shared "hashed files", and thus, risk having collision while writing them to disk?

Do you understand that any exception happening in PutToStorage will cause a connection leak, and that the proposed change is not fixing it at all?

This is just making it harder to click... and debug the root cause of this.

**Comment by xponen** [comment]
@shaun0x00  I know it isn't root fix, but downloading same name twice need to be fixed, no choice.
