### ISSUE TITLE
Mission Editor crashes after clicking New Mission

### ISSUE THREAD

**Issue by WiredTigerZK** [ZeroK-RTS/Zero-K-Infrastructure#932]
So I downloaded the mission editor from http://zero-k.info/Wiki/MissionEditorStartPage and got it to install eventually, after several tries of it failing and saying the repository was corrupt. I didn't get this error on the final try and everything appeared to download okay.

(As a side note, the mission editor download link from the Zero-K Lobby's Singleplayer page is broken; it tries to go to https://code.google.com/archive/p/zero-k/wikis/MissionEditorStartPage.wiki, which apparently doesn't exist.)

Then when I ran it, set my spring directory and clicked New Mission, I got an immediate error.

The error message from the MissionEditorErrors.txt file is:

Version: 2.4.2.2
Date: 31/01/2016 14:56:05
UnitSyncException
Unitsync initialization failed.
   at CMissionLib.UnitSyncLib.UnitSync..ctor(String path)
   at MissionEditor2.WelcomeDialog.<>c__DisplayClass13_0.<PromptForNewMission>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

There is an error report submission dialog but the progress bar just keeps moving and it doesn't do anything.

**Comment by KingRaptor** [comment]
You pointed Mission Editor to the .exe of your Spring 100 install, right? And Spring itself runs fine?

I'll fix the download link.

(Hmm, I probably broke the current release version anyway, it uploads to test server instead of the live one. Fix now published to the same location. Sorry!)

**Comment by KingRaptor** [comment]
(It was broke again. Had to republish a second time. Sorry .__.)

**Comment by WiredTigerZK** [comment]
Redownloaded the files.

Changing my Spring.exe path from **D:\Program Files (x86)\Spring\spring.exe** to **D:\Program Files (x86)\Spring\engine\100.0\spring.exe** seems to have done the trick. Hopefully my silly mistake will help other people who are having trouble.

Thanks for the help.

**Comment by KingRaptor** [comment]
Okay, good to hear! I've updated the Mission Editor tutorial (with the still-broken images, yeah) with that tip.
